cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add-cart/<int:item_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('reduce-quantity/<int:item_id>/', views.reduce_quantity, name='reduce_quantity'),
    path('cart-item-remove/<int:item_id>/', views.cart_item_remove, name='cart_item_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('item/', include('item.urls')),
    path('', include('order.urls')),
    path('cart/', include('cart.urls')),
]

# 開発サーバーでメディアファイルを配信するための設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('item-list/', views.ItemListView.as_view(), name="item_list"),
    path('item-create/', views.ItemCreateView.as_view(), name="item_create"),
    path('item-detail/<int:pk>/', views.ItemDetailView.as_view(), name="item_detail"),
    path('item-update/<int:pk>/', views.ItemUpdateView.as_view(), name="item_update"),
    path('item-delete/<int:pk>/', views.ItemDeleteView.as_view(), name="item_delete"),
    path('order-item-list/', views.OrderItemListView.as_view(), name="order_item_list"),
    path('search-item-list/', views.SearchItemListView.as_view(), name="search_item_list"),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('index/', views.IndexView.as_view(), name="index"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('order-confirm/', views.order_confirm, name='order_confirm'),
    path('order-create/', views.order_create, name='order_create'),
    path('placed-order-list/', views.PlacedOrderListView.as_view(), name="placed_order_list"),
    path('received-order-list/', views.received_order_list, name="received_order_list"),
]

cart/models.py
from django.db import models
from item.models import Item
from accounts.models import CustomUser
from django.utils import timezone
from django.urls import reverse


class CartItem(models.Model):
    """カートアイテムモデル"""
    class Meta:
        # アプリケーション名
        app_label = 'cart'
        # テーブル名
        db_table = 'cart_item'
        # django 管理画面の表示、名前末尾に s は表示されない
        verbose_name_plural = 'カートアイテム'

    item = models.ForeignKey(Item, verbose_name='商品', on_delete=models.CASCADE)
    quantity = models.IntegerField(verbose_name='数量', default=0)
    is_active = models.BooleanField(default=True)
    buyer = models.ForeignKey(
        CustomUser,
        verbose_name='購入者',
        on_delete=models.PROTECT,
        related_name='buyer_in_cart_item',
        blank=True,
        null=True
    )
    create_at = models.DateTimeField(verbose_name='カート作成日時',
                                     default=timezone.now)

    def sub_total(self):
        return self.item.price * self.quantity

    def __str__(self):
        return str(self.item.id)

    def get_absolute_url(self):
        return reverse("item:item_detail", kwargs={'pk': self.item.pk})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from item.models import Item
from .models import CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib import messages

import math

__tax_rate__ = 1.1


@login_required
def add_cart(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    cart_item, created = CartItem.objects.get_or_create(item=item, buyer=request.user, is_active=True)

    if item.stock > 0:
        try:
            if item.stock > cart_item.quantity:
                cart_item.quantity += 1
            cart_item.save()
        except Exception as e:
            print(e)
    else:
        pass

    return redirect('cart:cart_detail')


@login_required
def cart_detail(request, total=0, counter=0, cart_items=None,):
    warning_msg = {}
    try:
        cart_items = CartItem.objects.filter(buyer=request.user, is_active=True).order_by('-pk')
        error_msg = {}
        for cart_item in cart_items:
            if cart_item.item.stock > 0:
                if cart_item.item.stock > cart_item.quantity:
                    if cart_item.item.including_tax:
                        total += math.floor(cart_item.item.price * cart_item.quantity)
                        counter += cart_item.quantity
                    else:
                        total += math.floor(cart_item.item.price * cart_item.quantity * __tax_rate__)
                        counter += cart_item.quantity
                else:
                    if cart_item.item.including_tax:
                        total += math.floor(cart_item.item.price * cart_item.quantity)
                        warning_msg[cart_item.item_id] = 'こちらの商品は現在、在庫数が' + str(cart_item.item.stock) + cart_item.item.unit + 'です。'
                        cart_item.quantity = cart_item.item.stock
                        cart_item.save()
                    else:
                        total += math.floor(cart_item.item.price * cart_item.quantity * __tax_rate__)
                        warning_msg[cart_item.item_id] = 'こちらの商品は現在、在庫数が' + str(cart_item.item.stock) + cart_item.item.unit + 'です。'
                        cart_item.quantity = cart_item.item.stock
                        cart_item.save()
            else:
                total += math.floor(cart_item.item.price * cart_item.quantity * __tax_rate__)
                warning_msg[cart_item.item_id] = 'こちらの商品は現在、在庫がありません。'
                cart_item.quantity = 0
                cart_item.save()
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(warning_msg=warning_msg, cart_items=cart_items, total=total))


@login_required
def reduce_quantity(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    cart_item = CartItem.objects.get(item=item, buyer=request.user, is_active=True)

    if item.stock >= cart_item.quantity:
        cart_item.quantity -= 1   # 数量を1減らす
        if cart_item.quantity < 1:
            cart_item.is_active = False
        cart_item.save()
    else:
        messages.error(request, 'こちらの商品は現在、在庫数が' + item.stock + 'です。')

    return redirect('cart:cart_detail')


@login_required
def cart_item_remove(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    cart_item = CartItem.objects.get(item=item, buyer=request.user, is_active=True)

    cart_item.is_active = False
    cart_item.save()

    return redirect('cart:cart_detail')

templates/cart/cart.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    これはショッピングカートのページです。商品を確認し、注文してください。
{% endblock %}

{% block title %}ショッピングカート | Juhatchu{% endblock %}

{% block content_title %}Cart - Juhatchu{% endblock %}

{% block contents %}

    {% if not cart_items %}
        <div>
          <div class="text-center">
            <br>
            <h1 class="text center my_title">Your shopping cart is empty</h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'item:order_item_list' %}">here</a> to continue shopping.
            </p>
          </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    ショッピングカート
                </h1>
            </div>
            <br>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-lg-8 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                商品
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                {% if cart_item.item.photo %}
                                    <a href="{{ cart_item.get_absolute_url }}"><img src="{{cart_item.item.photo.url}}" alt="" class="float-center item-photo"></a>
                                {% else %}
                                    <a href="{{ cart_item.get_absolute_url }}"><p class="No-image">No image</p></a>
                                {% endif %}
                            </td>
                            <td class="text-left">
                                {{cart_item.item.name}}
                                <br>
                                商品ID: {{cart_item.item.id}}
                                <br>
                                単価: ￥{{cart_item.item.price}}
                                <br>
                                数量: <span id="item-quantity">{{cart_item.quantity}}</span> x ￥{{cart_item.item.price}}
                            </td>
                            <td>
                                ￥{{cart_item.sub_total}}（税抜）
                            </td>
                            {% if cart_item.item.available_stock > 0 %}
                                <td>在庫数：{{ cart_item.item.available_stock }}{{ cart_item.item.unit }}</td>
                                <td>
                                    <a href="{% url 'cart:add_cart' cart_item.item.id %}" class="increase-quantity">
                                        <i class="fas fa-plus-circle custom_icon"></i>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'cart:reduce_quantity' cart_item.item.id %}" class="reduce-quantity">
                                        <i class="fas fa-minus-circle custom_icon"></i>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'cart:cart_item_remove' cart_item.item.id %}" class="item-remove">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </td>
                            {% else %}
                                <td>Out of stock</td>
                                <td>
                                    &nbsp;
                                    <a href="{% url 'cart:reduce_quantity' cart_item.item.id %}" class="custom_a">
                                        <i class="fas fa-minus-circle custom_icon"></i>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'cart:cart_item_remove' cart_item.item.id %}" class="custom_item">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-lg-4 text-center">
                <table class="table my_custom_table">
                  <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                        <td>
                            ご注文のお支払いに進む前に、ショッピングカートの商品を確認してください
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            合計金額（税込）: <strong>￥{{ total }}</strong>
                        </td>
                    </tr>
                  </tbody>
                </table>
                <div class="mx-auto">
                    <a href="{% url 'order:order_create' %}" class="btn-primary btn-block submit-order">発注する</a>
                </div>
                <div class="mx-auto">
                    <a href="{% url 'item:order_item_list' %}" class="btn-secondary btn-block margin-top-5px">ショッピングを続ける</a>
                </div>
            </div>
        </div>
        <br>
    {% endif %}

{% endblock %}