cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add-cart/<int:item_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('reduce-quantity/<int:item_id>/', views.reduce_quantity, name='reduce_quantity'),
    path('cart-item-remove/<int:item_id>/', views.cart_item_remove, name='cart_item_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('item/', include('item.urls')),
    path('', include('order.urls')),
    path('cart/', include('cart.urls')),
]

# 開発サーバーでメディアファイルを配信するための設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('item-list/', views.ItemListView.as_view(), name="item_list"),
    path('item-create/', views.ItemCreateView.as_view(), name="item_create"),
    path('item-detail/<int:pk>/', views.ItemDetailView.as_view(), name="item_detail"),
    path('item-update/<int:pk>/', views.ItemUpdateView.as_view(), name="item_update"),
    path('item-delete/<int:pk>/', views.ItemDeleteView.as_view(), name="item_delete"),
    path('order-item-list/', views.OrderItemListView.as_view(), name="order_item_list"),
    path('search-item-list/', views.SearchItemListView.as_view(), name="search_item_list"),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('index/', views.IndexView.as_view(), name="index"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('order-confirm/', views.order_confirm, name='order_confirm'),
    path('order-create/', views.order_create, name='order_create'),
    path('placed-order-list/', views.PlacedOrderListView.as_view(), name="placed_order_list"),
    path('received-order-list/', views.received_order_list, name="received_order_list"),
]

order/models.py
from accounts.models import CustomUser
from django.db import models
from django.utils import timezone


class Order(models.Model):
    """注文モデル"""
    class Meta:
        app_label = 'order'
        # テーブル名
        db_table = 'order'
        # django 管理画面の表示、名前末尾に s は表示されない
        verbose_name_plural = '注文明細'
        ordering = ['-order_date']

    # カラム定義
    buyer = models.ForeignKey(CustomUser, verbose_name='購入者', on_delete=models.PROTECT, related_name='buyer_in_order')
    seller = models.ForeignKey(CustomUser, verbose_name='販売者', on_delete=models.PROTECT, related_name='seller')
    item_id = models.CharField(verbose_name='商品ID', max_length=40, default='dummy_item_id')
    name = models.CharField(verbose_name='商品名', max_length=40, default='dummy_name')
    price = models.IntegerField(verbose_name='単価', default=0)
    including_tax = models.BooleanField(verbose_name='税込', default=False)
    quantity = models.IntegerField(verbose_name='数量', default=0)
    unit = models.CharField(verbose_name='単位', max_length=10, default='個')
    moq = models.IntegerField(verbose_name='最低発注数量', blank=True, null=True, default=0)
    spq = models.IntegerField(verbose_name='最小発注単位', blank=True, null=True, default=0)
    photo = models.ImageField(verbose_name='商品画像', blank=True, null=True)
    total_unit = models.IntegerField(verbose_name='商品点数', default=0)
    total_price = models.IntegerField(verbose_name='合計金額', default=0)
    order_date = models.DateTimeField(verbose_name='注文日', default=timezone.now)
    delivery_date = models.DateTimeField(verbose_name='納品日', blank=True, null=True)
    shipment_date = models.DateTimeField(verbose_name='発送日', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='納品完了フラグ', default=True)
    is_cancel = models.BooleanField(verbose_name='キャンセル', default=False)
    remarks = models.TextField(verbose_name='備考', max_length=150, blank=True, null=True)
    updated_at = models.DateTimeField(verbose_name='更新日', auto_now=True)

order/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Order

import os


# 問合せフォーム
class ContactForm(forms.Form):
    last_name = forms.CharField(label='', max_length=30)
    first_name = forms.CharField(label='', max_length=30)
    email = forms.EmailField(label='',)
    subject = forms.CharField(label='', max_length=30)
    message = forms.CharField(label='', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['last_name'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'

        self.fields['first_name'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'

        self.fields['email'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['email'].widget.attrs['placeholder'] = 'Email Address'

        self.fields['subject'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['subject'].widget.attrs['placeholder'] = 'Subject'

        self.fields['message'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['message'].widget.attrs['id'] = 'id_message'
        self.fields['message'].widget.attrs['rows'] = '5'
        self.fields['message'].widget.attrs['placeholder'] = 'Message'

    #   メール送信関数
    def send_email(self):
        name = self.cleaned_data['last_name'] + " " + self.cleaned_data['first_name']
        email = self.cleaned_data['email']
        subject = self.cleaned_data['subject']
        message = self.cleaned_data['message']

        subject = '【お問い合せ】 {}'.format(subject)
        body_for_from = '問合せ者名： {0}\n問合せ者メールアドレス: {1}\n【メッセージ】\n{2}'.format(name, email, message)
        body_for_questioner = '問合せ者名： {0}\n問合せ者メールアドレス: {1}\n【メッセージ】\n{2}'.format(name, email, message)
        from_email = os.environ.get('DEFAULT_FROM_EMAIL')
        to_list_for_from = [
            os.environ.get('DEFAULT_FROM_EMAIL')
        ]
        to_list_for_questioner = [
           email
        ]

        message_from = EmailMessage(subject=subject, body=body_for_from, from_email=from_email, to=to_list_for_from)
        message_questioner = EmailMessage(
            subject=subject,
            body=body_for_questioner,
            from_email=from_email,
            to=to_list_for_questioner
        )

        message_from.send()
        message_questioner.send()


# オーダー編集フォーム
class OrderUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Order
        fields = '__all__'


# オーダー編集フォームセット
OrderUpdateFormSetBySeller =\
    forms.modelformset_factory(
        Order,
        fields=('id', 'is_active',),
        form=OrderUpdateForm,
        extra=0
    )

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail

from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic

from order.models import Order
from cart.models import CartItem
from item.models import Item

from .forms import ContactForm, OrderUpdateFormSetBySeller

import os
import math

logger = logging.getLogger(__name__)

__tax_rate__ = 1.1


# indexページの表示
class IndexView(generic.TemplateView):
    template_name = "order/index.html"


# お問い合わせ機能
class ContactView(generic.FormView):
    template_name = "order/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy('order:contact')

    def form_valid(self, form):
        name = form.cleaned_data['last_name'] + " " + form.cleaned_data['first_name']

        form.send_email()
        messages.success(self.request, 'メッセージを送信しました!!')
        logger.info('contact send by {}'.format('name'))

        return super().form_valid(form)


# 発注商品リストを表示
class PlacedOrderListView(LoginRequiredMixin, generic.ListView):
    template_name = 'order/placed_order_list.html'
    model = Order
    paginate_by = 5

    def get_queryset(self):
        order_items = Order.objects.filter(buyer=self.request.user).order_by('-pk')
        return order_items


def order_confirm(request, total=0, counter=0, cart_items=None):
    try:
        cart_items = CartItem.objects.filter(buyer=request.user, is_active=True).order_by('pk')
        warning_msg = {}
        for cart_item in cart_items:
            if cart_item.item.stock > 0:
                if cart_item.item.stock > cart_item.quantity:
                    if cart_item.item.including_tax:
                        total += math.floor(cart_item.item.price * cart_item.quantity)
                    else:
                        total += math.floor(cart_item.item.price * cart_item.quantity * __tax_rate__)
                else:
                    if cart_item.item.including_tax:
                        total += math.floor(cart_item.item.price * cart_item.quantity)
                    else:
                        total += math.floor(cart_item.item.price * cart_item.quantity * __tax_rate__)
                    warning_msg[cart_item.item_id] = 'こちらの商品は現在、在庫数が' + str(cart_item.item.stock) + cart_item.item.unit + 'です。'
            else:
                if cart_item.item.including_tax:
                    total += math.floor(cart_item.item.price * cart_item.quantity)
                else:
                    total += math.floor(cart_item.item.price * cart_item.quantity * __tax_rate__)
                warning_msg[cart_item.item_id] = 'こちらの商品は現在、在庫数がありません。'
    except ObjectDoesNotExist:
        pass
    return render(request, 'order_confirm.html', dict(cart_items=cart_items, total=total, warning_msg=warning_msg))


def order_create(request):

    all_items_total_price = 0
    item_name_quantity_for_sending_email = {}
    counter = 0

    try:
        cart_items = CartItem.objects.filter(buyer=request.user, is_active=True).order_by('-pk')
        # Orderモデルインスタンス作成
        for cart_item in cart_items:
            if cart_item.quantity != 0 and cart_item.quantity <= cart_item.item.stock:
                # Itemモデルのstock（在庫数）フィールドを発注分減らし、is_activeフィールドをFalseに更新
                item = Item.objects.get(pk=cart_item.item.id)
                item.stock -= cart_item.quantity
                cart_item.is_active = False

                item.save()

                if cart_item.item.including_tax:
                    total_price = (cart_item.item.price * cart_item.quantity)
                    total_unit = cart_item.quantity
                    all_items_total_price += total_price
                else:
                    total_price = (cart_item.item.price * cart_item.quantity * __tax_rate__)
                    total_unit = cart_item.quantity
                    all_items_total_price += total_price

                item_name_quantity_for_sending_email[cart_item.item.name] = str(cart_item.quantity) + cart_item.item.unit

                order = Order.objects.create(
                    buyer=request.user,
                    seller=cart_item.item.user,
                    item_id=cart_item.item.pk,
                    name=cart_item.item.name,
                    price=cart_item.item.price,
                    including_tax=cart_item.item.including_tax,
                    quantity=cart_item.quantity,
                    unit=cart_item.item.unit,
                    moq=cart_item.item.moq,
                    spq=cart_item.item.spq,
                    photo=cart_item.item.photo,
                    total_unit=total_unit,
                    total_price=total_price,
                )
                order.save()
                cart_item.quantity = 0
                cart_item.save()
                counter += 1

    except ObjectDoesNotExist:
        pass

    if counter > 0:
        messages.success(request, '発注が完了しました。詳細は発注履歴一覧でご覧いただけます。')

        try:
            # 発注情報メール件名
            subject = "Juhatchu 発注情報"
            # 受注情報メールメッセージ
            message_for_seller = str(request.user)\
                + "様から発注がありました。\n詳細は、受注一覧より確認いただけます。\n"\
                + "----------------------------------------\n"\
                + str("\n"
                      .join(["{0} - {1}"
                            .format(key, value) for (key, value) in item_name_quantity_for_sending_email.items()]))
            # 受注情報メールメッセージfor DEFAULT_FROM_EMAIL
            message_for_from = str(request.user) \
                      + "様から発注がありました。\n詳細は、受注一覧より確認いただけます。\n" \
                      + "----------------------------------------\n" \
                      + str("\n"
                            .join(["{0} - {1}"
                                  .format(key, value) for (key, value) in item_name_quantity_for_sending_email.items()]))

            # 送信元アドレス
            from_email = os.environ.get('DEFAULT_FROM_EMAIL')
            # 送信先アドレス
            seller = cart_item.item.user.email
            recipient_list_for_seller = [seller]
            recipient_list_for_from = [os.environ.get('DEFAULT_FROM_EMAIL')]
            # メール送信
            send_mail(subject, message_for_seller, from_email, recipient_list_for_seller)
            send_mail(subject, message_for_from, from_email, recipient_list_for_from)
        except ObjectDoesNotExist:
            pass

        return redirect('order:placed_order_list')

    return redirect('cart:cart_detail')


def received_order_list(request):

    if request.user.is_anonymous:
        return redirect('account_login')
    else:
        formset = OrderUpdateFormSetBySeller(
            request.POST or None, queryset=Order.objects.filter(seller=request.user)
        )
        order_list = Order.objects.filter(seller=request.user)

        if request.method == 'POST' and formset.is_valid():
            formset.save()
            return redirect('order:received_order_list')

        context = {
            'formset': formset,
            'order_list': order_list,
        }

        return render(request, 'order/received_order_list.html', context)


"""
class FavoriteItemCreateView(generic.CreateView):
    template_name = 'order/favorite_item_create.html'
    model = FavoriteItem
    form_class = FavoriteItemCreateForm
    success_url = reverse_lazy('order:index')

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super().get_form_kwargs(*args, **kwargs)
        form_kwargs['initial'] = {'user': self.request.user, 'item': self.kwargs.get('pk')}  # フォームに初期値を設定する。
        print(self.request)
        print(self.args)
        print(self.kwargs)
        print(self.kwargs.get('pk'))
        print(self.kwargs.get('name'))
        print(form_kwargs)
        return form_kwargs

    def form_valid(self, form):
        FavoriteItem = form.save(commit=False)
        FavoriteItem.user = self.request.user
        FavoriteItem.item = self.kwargs.get('pk')

        FavoriteItem.save()

        messages.success(self.request, '商品を登録しました。')

        return super().form_valid(form)
"""

templates/order/favorite_item_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}

    <h1>商品登録</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <hr>
        <div class="item-edit-button">
            <button class="btn btn-primary item-edit-button" type="submit">保存</button>
        </div>
    </form>

{% endblock %}

templates/order/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}INDEX | Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}
    {% if messages %}
        <div class="send_message" hidden><!-- メッセージを削除するため{{ message }}を記述し、非表示にするためにhidden属性を設定 -->
            <ul style="list-style: none">
                {% for message in messages %}
                <li>
                    <p>{{ message }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div class="col-xl-12">
        <h1 class="mt-4">Juhatchu</h1>
        <p>Juhatchu is ordering system</p>
    </div>
{% endblock %}

templates/order/item_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}X-order{% endblock %}

{% block content_title %}X-order{% endblock %}

{% block contents %}

    <div class="delete-check"><p>以下の商品をほんとうに削除しますか？</p><p>削除する場合は、ページ下部の削除ボタンをクリックしてください。</p></div>
    <div>
        {% if item.photo %}
            <img src="{{ item.photo.url }}"  class="item-photo" />
        {% else %}
            <p class="No-image">No image</p>
        {% endif %}
    </div>
    <hr>
    <div class="margin-top-5px">
    <table class="table-bordered" id="dataTable">
        <tbody>
            <tr>
                <th>id</th>
                <td>{{ item.pk }}</td>
            </tr>
            <tr>
                <th>商品名</th>
                <td>{{ item.name }}</td>
            </tr>
            <tr>
                <th>価格</th>
                <td>{{ item.price }}</td>
            </tr>
            <tr>
                <th>税込</th>
                <td>{{ item.including_tax }}</td>
            </tr>
            <tr>
                <th>在庫数</th>
                <td>{{ item.stock }}{{ item.unit }}</td>
            </tr>
            <tr>
                <th>最低発注数量／最小発注単位</th>
                <td>{{ item.moq }}／{{ item.spq }}</td>
            </tr>
            <tr>
                <th>カテゴリー１</th>
                <td>{{ item.category1 }}</td>
            </tr>
            <tr>
                <th>カテゴリー２</th>
                <td>{{ item.category2 }}</td>
            </tr>
            <tr>
                <th>カテゴリー３</th>
                <td>{{ item.category3 }}</td>
            </tr>
            <tr>
                <th>登録日時</th>
                <td>{{ item.created_at }}</td>
            </tr>
            <tr>
                <th>最終更新日</th>
                <td>{{ item.updated_at }}</td>
            </tr>
        </tbody>
    </table>
    </div>
    <hr>
    <div class="item-edit-button">
        <form method="post">
            {% csrf_token %}
            <a class="btn btn-primary" href="{% url 'order:item_detail' object.pk %}">キャンセル</a>
            <button class="btn btn-primary ml-2" type="submit">削除</button>
        </form>
    </div>
{% endblock %}

templates/order/item_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}商品詳細{% endblock %}

{% block content_title %}X-order{% endblock %}

{% block contents %}

    <h2>商品詳細</h2>
    <div>
        {% if item.photo %}
            <img src="{{ item.photo.url }}"  class="item-photo" />
        {% else %}
            <p class="No-image">No image</p>
        {% endif %}
    </div>
    <hr>
    <div class="margin-top-5px">
    <table class="table-bordered" id="dataTable">
        <tbody>
            <tr>
                <th>id</th>
                <td>{{ item.pk }}</td>
            </tr>
            <tr>
                <th>商品名</th>
                <td>{{ item.name }}</td>
            </tr>
            <tr>
                <th>価格</th>
                <td>{{ item.price }}</td>
            </tr>
            <tr>
                <th>税込／税抜</th>
                <td>
                    {% if item.including_tax %}
                        <div>税込</div>
                    {% else %}
                        <div>税抜</div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>在庫数</th>
                <td>{{ item.stock }}{{ item.unit }}</td>
            </tr>
            <tr>
                <th>最低発注数量／最小発注単位</th>
                <td>{{ item.moq }}／{{ item.spq }}</td>
            </tr>
            <tr>
                <th>カテゴリー１</th>
                <td>{{ item.category1 }}</td>
            </tr>
            <tr>
                <th>カテゴリー２</th>
                <td>{{ item.category2 }}</td>
            </tr>
            <tr>
                <th>カテゴリー３</th>
                <td>{{ item.category3 }}</td>
            </tr>
            <tr>
                <th>販売可否</th>
                <td>
                    {% if item.is_active %}
                        <div>可</div>
                    {% else %}
                        <div>否</div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>登録日時</th>
                <td>{{ item.created_at }}</td>
            </tr>
            <tr>
                <th>最終更新日</th>
                <td>{{ item.updated_at }}</td>
            </tr>
        </tbody>
    </table>
    </div>
    <hr>
    <div class="item-edit-button">
        {% if user.is_authenticated and user == item.user %}
            <a class="btn btn-primary btn-user" href="{% url 'order:item_update' object.pk %}">編集</a>
        {% else %}
            <a class="btn btn-primary btn-user" href="{% url 'order:favorite_item_create' item.pk item.name %}">お気に入り登録</a>
        {% endif %}
        <a href="{% url 'order:item_delete' item.pk%}" class="btn btn-primary btn-user">削除</a>
    </div>
{% endblock %}

templates/order/item_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}X-order{% endblock %}

{% block content_title %}X-order{% endblock %}

{% block contents %}
    <table class="table table-bordered" id="dataTable">
      <thead>
        <tr>
          <th>id</th>
          <th></th>
          <th>商品名</th>
          <th>価格</th>
          <th>税込</th>
          <th>在庫数</th>
          <th>商品詳細</th>
          <th>編集</th>
        </tr>
      </thead>
      <tbody>
        {% for item in item_list %}
          <tr>
            <td>{{ item.pk }}</td>
            <td>
              {% if item.photo %}
                <img src="{{ item.photo.url }}" class="item-photo"/></td>
              {% else %}
                <p>No image</p>
              {% endif %}
            <td>{{ item.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.including_tax }}</td>
            <td>{{ item.stock }}{{ item.unit }}</td>
            <td><a href="{% url 'order:item_detail' item.pk%}"><i class="fas fa-info-circle fa-lg"></i></a></td>
            <td><a href="{% url 'order:item_update' item.pk%}"><i class="fas fa-edit fa-lg"></i></a></td>
          </tr>
        {% empty %}
          <p>まだ商品が登録されておりません。</p>
        {% endfor %}
      </tbody>
    </table>

    <!-- ページネーション処理 -->
    {% if is_paginated %}
      <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              <span>&laquo;</span>
            </a>
          </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item" active><a class="page-link" href="#">{{ page_num }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
          {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              <span>&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    {% endif %}

{% endblock %}

templates/order/item_update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}X-order{% endblock %}

{% block content_title %}X-order{% endblock %}

{% block contents %}

    <h1>商品登録情報更新</h1>
    <hr class="hr-item-create-update">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <div class="form-table">
                {{ form.as_table }}
            </div>
        </table>
        <hr>
        <div class="item-edit-button">
            <a class="btn btn-primary btn-user" href="{% url 'order:item_detail' object.pk %}">キャンセル</a>
            <button class="btn btn-primary btn-user ml-2" type="submit">更新</button>
        </div>
    </form>

{% endblock %}

templates/order/order_confirm.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    これは発注確認ページです。商品を確認し、注文してください。
{% endblock %}

{% block title %}発注確認 | Juhatchu{% endblock %}

{% block content_title %}Oder Confirm - Juhatchu{% endblock %}

{% block contents %}

    {% if not cart_items %}
        <div>
          <div class="text-center">
            <br>
            <h1 class="text center my_title">Your shopping cart is empty</h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'item:order_item_list' %}">here</a> to continue shopping.
            </p>
          </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    発注確認
                </h1>
            </div>
            <br>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-lg-8 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                商品
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                {% if cart_item.item.photo %}
                                    <a href="{{ cart_item.get_absolute_url }}"><img src="{{cart_item.item.photo.url}}" alt="" class="float-center item-photo"></a>
                                {% else %}
                                    <a href="{{ cart_item.get_absolute_url }}"><p class="No-image">No image</p></a>
                                {% endif %}
                            </td>
                            <td class="text-left">
                                {{cart_item.item.name}}
                                <br>
                                商品ID: {{cart_item.item.id}}
                                <br>
                                単価: ￥{{cart_item.item.price}}
                                <br>
                                在庫数: <span id="item-quantity">{{cart_item.item.stock}}</span>
                            </td>
                            <td>
                                <div class="container">
                                    <div class="row">

                                    {% if cart_item.item.stock > 0 %}
                                        <div class="col">
                                            数量：{{ cart_item.quantity }}{{ cart_item.item.unit }} x 単価：￥{{ cart_item.item.price }}
                                        </div>
                                    {% else %}
                                        <div class="col-4">Out of stock</div>
                                        <div class="col-3">
                                            <a href="{% url 'cart:cart_item_remove' cart_item.item.id %}" class="item-remove">
                                                <i class="far fa-trash-alt"></i>
                                            </a>
                                        </div>
                                    {% endif %}
                                        <div class="col">
                                            合計金額：￥{{cart_item.sub_total}}（税抜）
                                        </div>
                                    </div>
                                    {% for key, val in warning_msg.items %}
                                        {% if key == cart_item.item_id %}
                                            {% if cart_item.item.stock < cart_item.quantity or cart_item.item.stock == 0 %}
                                                <div class="row message_about_stock mt-4 alert alert-warning" role="alert">
                                                    {{ val }}
                                                </div>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-lg-4 text-center">
                <table class="table my_custom_table">
                  <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                        <td>
                            ご注文のお支払いに進む前に、ショッピングカートの商品を確認してください
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            総合計金額（税込）: <strong>￥{{ total }}</strong>
                        </td>
                    </tr>
                  </tbody>
                </table>
                {% if total > 0 %}
                    <div class="mx-auto">
                        <a href="{% url 'order:order_create' %}" class="btn btn-primary btn-user btn-block submit-order">
                            <i class="fas fa-fax mr-2"></i>発注する
                        </a>
                    </div>
                {% endif %}
                <div class="mx-auto">
                    <a href="{% url 'item:order_item_list' %}" class="btn btn-secondary btn-user btn-block margin-top-5px">ショッピングを続ける</a>
                </div>
            </div>
        </div>
        <br>
    {% endif %}

{% endblock %}