cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add-cart/<int:item_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('reduce-quantity/<int:item_id>/', views.reduce_quantity, name='reduce_quantity'),
    path('cart-item-remove/<int:item_id>/', views.cart_item_remove, name='cart_item_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('item/', include('item.urls')),
    path('', include('order.urls')),
    path('cart/', include('cart.urls')),
]

# 開発サーバーでメディアファイルを配信するための設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('item-list/', views.ItemListView.as_view(), name="item_list"),
    path('item-create/', views.ItemCreateView.as_view(), name="item_create"),
    path('item-detail/<int:pk>/', views.ItemDetailView.as_view(), name="item_detail"),
    path('item-update/<int:pk>/', views.ItemUpdateView.as_view(), name="item_update"),
    path('item-delete/<int:pk>/', views.ItemDeleteView.as_view(), name="item_delete"),
    path('order-item-list/', views.OrderItemListView.as_view(), name="order_item_list"),
    path('search-item-list/', views.SearchItemListView.as_view(), name="search_item_list"),
]

item/models.py
from accounts.models import CustomUser
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MinValueValidator


class Item(models.Model):
    """商品モデル"""
    class Meta:
        app_label = 'item'
        # テーブル名
        db_table = 'item'
        # django 管理画面の表示、名前末尾に s は表示されない
        verbose_name_plural = '商品'

    # カラム定義
    user = models.ForeignKey(CustomUser, verbose_name='販売者', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='商品名', max_length=40)
    item_description = models.TextField(verbose_name='商品説明', max_length=200, blank=True, null=True)
    price = models.IntegerField(verbose_name='単価', default=0)
    including_tax = models.BooleanField(verbose_name='税込', default=False)
    unit = models.CharField(verbose_name='単位', max_length=10, default='個')
    stock = models.IntegerField(verbose_name='実在庫数', validators=[MinValueValidator(0)], default=0)
    moq = models.IntegerField(verbose_name='最低発注数量', blank=True, null=True, default=0)
    spq = models.IntegerField(verbose_name='最小発注単位', blank=True, null=True, default=0)
    category1 = models.CharField(verbose_name='カテゴリ1', max_length=30, blank=True, null=True)
    category2 = models.CharField(verbose_name='カテゴリ2', max_length=30, blank=True, null=True)
    category3 = models.CharField(verbose_name='カテゴリ3', max_length=30, blank=True, null=True)
    photo = models.ImageField(verbose_name='商品画像', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    is_active = models.BooleanField(verbose_name='販売可否', default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("item:item_detail", kwargs={'pk': self.pk})

item/forms.py
from django import forms
from item.models import Item


class ItemCreateForm(forms.ModelForm):
    # 商品登録フォーム
    class Meta:
        model = Item
        fields = (
                    "name",
                    "item_description",
                    "price",
                    "including_tax",
                    "unit",
                    "stock",
                    "moq",
                    "spq",
                    "category1",
                    "category2",
                    "category3",
                    "is_active",
                    "photo"
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        """
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control form-control-user'

        # 'item_description' フィールドに 'class'属性を設定
        self.fields['item_description'].widget.attrs.update({
            'class': 'item-description',
        })
        """


class ItemUpdateForm(forms.ModelForm):
    # 商品登録フォーム
    class Meta:
        model = Item
        fields = (
                    "name",
                    "item_description",
                    "price",
                    "including_tax",
                    "unit",
                    "stock",
                    "moq",
                    "spq",
                    "category1",
                    "category2",
                    "category3",
                    "is_active",
                    "photo"
        )

item/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
import logging

from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic

from item.models import Item
from django.db.models import Q

from .forms import ItemCreateForm, ItemUpdateForm

logger = logging.getLogger(__name__)


class ItemCreateView(LoginRequiredMixin, generic.CreateView):
    """販売商品登録機能"""
    template_name = "item/item_create.html"
    model = Item
    form_class = ItemCreateForm
    success_url = reverse_lazy('item:item_list')

    def form_valid(self, form):
        item = form.save(commit=False)
        item.user = self.request.user
        item.save()

        messages.success(self.request, '商品を登録しました。')

        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '商品の登録に失敗しました。お手数ですが、はじめから登録をやり直してください。')

        return super().form_invalid(form)


class ItemListView(LoginRequiredMixin, generic.ListView):
    """登録商品一覧機能"""
    template_name = 'item/item_list.html'
    model = Item
    paginate_by = 3

    def get_queryset(self):
        items = Item.objects.filter(user=self.request.user).order_by('pk')
        return items


class ItemDetailView(generic.DetailView):
    """商品詳細表示機能"""
    template_name = 'item/item_detail.html'
    model = Item


class ItemUpdateView(LoginRequiredMixin, generic.UpdateView):
    """登録商品編集"""
    template_name = 'item/item_update.html'
    model = Item
    form_class = ItemUpdateForm

    def get_success_url(self):
        return reverse_lazy('item:item_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        item = Item.objects.get(pk=self.object.pk)
        form_item = form.save(commit=False)
        form_item.user = self.request.user

        item.save()

        messages.success(self.request, '商品詳細を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '商品詳細の更新に失敗しました。')
        return super().form_invalid(form)


class ItemDeleteView(LoginRequiredMixin, generic.DeleteView):
    """登録商品削除機能"""
    template_name = 'item/item_delete.html'    # 削除確認画面
    model = Item
    success_url = reverse_lazy('item:item_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "商品を削除しました。")
        return super().delete(request, *args, **kwargs)


class OrderItemListView(generic.ListView):

    """購入商品一覧機能"""
    template_name = 'item/order_item_list.html'
    model = Item
    paginate_by = 2

    def get_queryset(self):
        # ログイン済み会なかで処理を分岐
        if self.request.user.is_authenticated:
            items = Item.objects.all().exclude(user=self.request.user).order_by('pk')
            return items
        else:
            items = Item.objects.all().order_by('pk')
            return items


class SearchItemListView(generic.ListView):
    """商品検索結果表示"""
    template_name = 'item/search_item_list.html'
    model = Item
    paginate_by = 3


    def get_queryset(self):
        # ログイン済みか否かで処理を分岐
        if self.request.user.is_authenticated:
            # ログイン済み
            query = self.request.GET.get('query')
            select_item = self.request.GET.get('select-item')


            # select_itemがpurchase-itemかsales-itemかで分岐
            if select_item == 'purchase-items':

                # 購入商品検索(purchase-item)
                items = Item.objects.filter(
                    Q(name__icontains=query)
                    | Q(item_description__icontains=query)
                    | Q(category1__icontains=query)
                    | Q(category2__icontains=query)
                    | Q(category3__icontains=query)
                ).exclude(user=self.request.user).order_by('pk')

                # 検索結果件数
                count = Item.objects.filter(
                    Q(name__icontains=query)
                    | Q(item_description__icontains=query)
                    | Q(category1__icontains=query)
                    | Q(category2__icontains=query)
                    | Q(category3__icontains=query)
                ).exclude(user=self.request.user).order_by('pk').count()

                messages.success(self.request, query + 'を含む検索結果：' + str(count) + '件')

            else:

                # 販売商品検索(sales-item)
                items = Item.objects.filter(
                    Q(name__icontains=query)
                    | Q(item_description__icontains=query)
                    | Q(category1__icontains=query)
                    | Q(category2__icontains=query)
                    | Q(category3__icontains=query)
                ).filter(user=self.request.user).order_by('pk')

                # 検索結果件数
                count = Item.objects.filter(
                    Q(name__icontains=query)
                    | Q(item_description__icontains=query)
                    | Q(category1__icontains=query)
                    | Q(category2__icontains=query)
                    | Q(category3__icontains=query)
                ).filter(user=self.request.user).order_by('pk').count()

                messages.success(self.request, query + 'を含む検索結果：' + str(count) + '件')

            return items

        else:
            # ログイン未済
            query = self.request.GET.get('query')

            # 販売登録されたすべての商品を取得
            items = Item.objects.filter(
                Q(name__icontains=query)
                | Q(item_description__icontains=query)
                | Q(category1__icontains=query)
                | Q(category2__icontains=query)
                | Q(category3__icontains=query)
            ).order_by('pk')

            # レコード件数を取得
            count = Item.objects.filter(
                Q(name__icontains=query)
                | Q(item_description__icontains=query)
                | Q(category1__icontains=query)
                | Q(category2__icontains=query)
                | Q(category3__icontains=query)
            ).order_by('pk').count()

            messages.success(self.request, query + 'を含む検索結果：' + str(count) + '件')

        return items

templates/item/item_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %}商品登録 | Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}

    <h1>商品登録</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="item-create">
            {{ form.as_table }}
        </table>
        <hr>
        <div class="item-edit-button">
            <button class="btn btn-primary item-edit-button" type="submit">保存</button>
        </div>
    </form>

{% endblock %}

templates/item/item_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}

    <div class="delete-check"><p>以下の商品をほんとうに削除しますか？</p><p>削除する場合は、ページ下部の削除ボタンをクリックしてください。</p></div>
    <div>
        {% if item.photo %}
            <img src="{{ item.photo.url }}"  class="item-photo" />
        {% else %}
            <p class="No-image">No image</p>
        {% endif %}
    </div>
    <hr>
    <div class="margin-top-5px">
    <table class="table-bordered" id="dataTable">
        <tbody>
            <tr>
                <th>id</th>
                <td>{{ item.pk }}</td>
            </tr>
            <tr>
                <th>商品名</th>
                <td>{{ item.name }}</td>
            </tr>
            <tr>
                <th>商品説明</th>
                <td>{{ item.item_description }}</td>
            </tr>
            <tr>
                <th>価格</th>
                <td>{{ item.price }}</td>
            </tr>
            <tr>
                <th>税込</th>
                <td>{{ item.including_tax }}</td>
            </tr>
            <tr>
                <th>在庫数</th>
                <td>{{ item.stock }}{{ item.unit }}</td>
            </tr>
            <tr>
                <th>最低発注数量／最小発注単位</th>
                <td>{{ item.moq }}／{{ item.spq }}</td>
            </tr>
            <tr>
                <th>カテゴリー１</th>
                <td>{{ item.category1 }}</td>
            </tr>
            <tr>
                <th>カテゴリー２</th>
                <td>{{ item.category2 }}</td>
            </tr>
            <tr>
                <th>カテゴリー３</th>
                <td>{{ item.category3 }}</td>
            </tr>
            <tr>
                <th>登録日時</th>
                <td>{{ item.created_at }}</td>
            </tr>
            <tr>
                <th>最終更新日</th>
                <td>{{ item.updated_at }}</td>
            </tr>
        </tbody>
    </table>
    </div>
    <hr>
    <div class="item-edit-button">
        <form method="post">
            {% csrf_token %}
            <a class="btn btn-primary" href="{% url 'item:item_detail' object.pk %}">キャンセル</a>
            <button class="btn btn-primary ml-2" type="submit">削除</button>
        </form>
    </div>
{% endblock %}

templates/item/item_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}商品詳細 | Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}

    <div class="h3 font-weight-bold">商品詳細</div>
    <div class="d-flex">
      <div class="">
        {% if item.photo %}
            <img src="{{ item.photo.url }}"  class="item-photo" />
        {% else %}
            <p class="No-image">No image</p>
        {% endif %}
      </div>
      <div class="w-75 ml-4">
        <div class="h5 font-weight-bold">商品説明</div>
        <div class="item-description ml-2">{{ item.item_description }}</div>
      </div>
    </div>
    <hr>
    <div class="margin-top-5px">
    <table class="table-bordered" id="dataTable">
        <tbody>
            <tr>
                <th>id</th>
                <td>{{ item.pk }}</td>
            </tr>
            <tr>
                <th>商品名</th>
                <td>{{ item.name }}</td>
            </tr>

            <tr>
                <th>価格</th>
                <td>{{ item.price }}</td>
            </tr>
            <tr>
                <th>税込／税抜</th>
                <td>
                    {% if item.including_tax %}
                        <div>税込</div>
                    {% else %}
                        <div>税抜</div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>有効在庫数</th>
                {% if item.stock > 0 %}
                  <td>{{ item.stock }}{{ item.unit }}</td>
                {% else %}
                  <td>Out of stock</td>
                {% endif %}
            </tr>
            <tr>
                <th>最低発注数量／最小発注単位</th>
                <td>{{ item.moq }}／{{ item.spq }}</td>
            </tr>
            <tr>
                <th>カテゴリー１</th>
                <td>{{ item.category1 }}</td>
            </tr>
            <tr>
                <th>カテゴリー２</th>
                <td>{{ item.category2 }}</td>
            </tr>
            <tr>
                <th>カテゴリー３</th>
                <td>{{ item.category3 }}</td>
            </tr>
            <tr>
                <th>販売可否</th>
                <td>
                    {% if item.is_active %}
                        <div>可</div>
                    {% else %}
                        <div>否</div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>登録日時</th>
                <td>{{ item.created_at }}</td>
            </tr>
            <tr>
                <th>最終更新日</th>
                <td>{{ item.updated_at }}</td>
            </tr>
        </tbody>
    </table>
    </div>
    <hr>
    <div class="add-cart-button">
        {% if user.is_authenticated and user == item.user %}

        {% else %}
            {% if item.stock > 0 %}
                <a class="btn btn-primary" href="{% url 'cart:add_cart' item.id %}">カートに追加</a>
            {% else %}
                <span>現在、こちらの商品は取り扱いできません。</span><a class="btn btn-primary" href="{{request.META.HTTP_REFERER}}">戻る</a>
            {% endif %}
        {% endif %}
    </div>
    <div class="item-edit-button">
        {% if user.is_authenticated and user == item.user %}
            <a class="btn btn-primary btn-user" href="{% url 'item:item_update' object.pk %}">編集</a>
            <a href="{% url 'item:item_delete' item.pk%}" class="btn btn-primary btn-user">削除</a>
        {% else %}
            
        {% endif %}
    </div>
{% endblock %}

templates/item/item_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}登録商品一覧 | Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}
  <div class="table-responsive">
    <table class="table" id="dataTable">
      <thead class="thead-light col-4">
        <tr>
          <th scope="col">id</th>
          <th scope="col" class="">商品画像</th>
          <th scope="col">商品名</th>
          <th scope="col">価格</th>
          <th scope="col">税込</th>
          <th scope="col">在庫数</th>
          <th scope="col">商品詳細</th>
          <th scope="col">編集</th>
        </tr>
      </thead.thead-light>
      <tbody>
        {% for item in object_list %}
          <tr>
            <td>{{ item.pk }}</td>
            <td>
              {% if item.photo %}
                <a href="{{ item.get_absolute_url }}"><img src="{{ item.photo.url }}" class="item-photo"/></a>
              {% else %}
                <a href="{{ item.get_absolute_url }}"><p class="No-image">No image</p></a>
              {% endif %}
            </td>
            <td>{{ item.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.including_tax }}</td>
            {% if item.stock > 0 %}
              <td>{{ item.stock }}{{ item.unit }}</td>
            {% else %}
              <td>Out of stock</td>
            {% endif %}
            <td><a href="{% url 'item:item_detail' item.pk %}"><i class="fas fa-info-circle fa-lg"></i></a></td>
            <td><a href="{% url 'item:item_update' item.pk %}"><i class="fas fa-edit fa-lg"></i></a></td>
          </tr>
        {% empty %}
          <p>まだ商品が登録されておりません。</p>
        {% endfor %}
      </tbody>
    </table>
  </div>

    <!-- ページネーション処理 -->
    {% if is_paginated %}
      <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              <span>&laquo;</span>
            </a>
          </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item" active><a class="page-link" href="#">{{ page_num }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
          {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              <span>&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    {% endif %}

{% endblock %}

templates/item/item_update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}

    <h1>商品登録情報更新</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="item-create">
            <div class="form-table">
                {{ form.as_table }}
            </div>
        </table>
        <hr>
        <div class="item-edit-button">
            <a class="btn btn-primary btn-user" href="{% url 'item:item_detail' object.pk %}">キャンセル</a>
            <button class="btn btn-primary btn-user ml-2" type="submit">更新</button>
        </div>
    </form>

{% endblock %}

templates/item/order_item_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}商品一覧 | Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}
    <h1>商品リスト</h1>
     <table class="table table-bordered" id="dataTable">
      <thead>
        <tr>
          <th>id</th>
          <th class="item-photo">商品画像</th>
          <th>商品名</th>
          <th>価格</th>
          <th>税込</th>
          <th>在庫数</th>
          <th>商品詳細</th>
          <th>お気に入り登録</th>
        </tr>
      </thead>
      <tbody>
        {% for item in object_list %}
          <tr>
            <td>{{ item.pk }}</td>
            <td>
              {% if item.photo %}
                <a href="{{ item.get_absolute_url }}"><img src="{{ item.photo.url }}" class="item-photo"/></a>
              {% else %}
                <a href="{{ item.get_absolute_url }}"><p class="No-image">No image</p></a>
              {% endif %}
            </td>
            <td>{{ item.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.including_tax }}</td>
            {% if item.stock > 0 %}
              <td>{{ item.stock }}{{ item.unit }}</td>
            {% else %}
              <td>Out of stock</td>
            {% endif %}
            <td><a href="{% url 'item:item_detail' item.pk%}"><i class="fas fa-info-circle fa-lg"></i></a></td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- ページネーション処理 -->
    {% if is_paginated %}
      <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
              <span>&laquo;</span>
            </a>
          </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item" active><a class="page-link" href="#">{{ page_num }}</a></li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_num }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
                {{ page_num }}
              </a>
            </li>
          {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
              <span>&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    {% endif %}

{% endblock %}

templates/item/search_item_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}検索商品一覧 | Juhatchu{% endblock %}

{% block content_title %}Juhatchu{% endblock %}

{% block contents %}
    <h1>商品リスト</h1>
     <table class="table table-bordered" id="dataTable">
      <thead>
        <tr>
          <th>id</th>
          <th class="item-photo">商品画像</th>
          <th>商品名</th>
          <th>価格</th>
          <th>税込</th>
          <th>在庫数</th>
          <th>商品詳細</th>
        </tr>
      </thead>
      <tbody>
        {% for item in object_list %}
          <tr>
            <td>{{ item.pk }}</td>
            <td>
              {% if item.photo %}
                <a href="{{ item.get_absolute_url }}"><img src="{{ item.photo.url }}" class="item-photo"/></a>
              {% else %}
                <a href="{{ item.get_absolute_url }}"><p class="No-image">No image</p></a>
              {% endif %}
            </td>
            <td>{{ item.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.including_tax }}</td>
            {% if item.stock > 0 %}
              <td>{{ item.stock }}{{ item.unit }}</td>
            {% else %}
              <td>Out of stock</td>
            {% endif %}
            <td><a href="{% url 'item:item_detail' item.pk%}"><i class="fas fa-info-circle fa-lg"></i></a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- ページネーション処理 -->
    {% if is_paginated %}
      <ul class="pagination">
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
              <span>&laquo;</span>
            </a>
          </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item" active><a class="page-link" href="#">{{ page_num }}</a></li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_num }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
                {{ page_num }}
              </a>
            </li>
          {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
              <span>&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    {% endif %}

{% endblock %}